name: integrador
description: "A new Flutter project."

# Esta línea evita que el paquete se publique accidentalmente en pub.dev
publish_to: 'none' # Elimina esta línea si deseas publicar en pub.dev

# Versión de la aplicación
version: 1.0.0+1

# Ambiente del SDK
environment:
  sdk: '>=3.3.0 <4.0.0'

# Dependencias principales
dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^0.5.2
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  twilio_flutter: ^0.0.9
  shared_preferences: ^2.2.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.7+3
  image: ^3.2.0
  mobile_scanner: ^2.1.0

# Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# Configuración de Flutter
flutter:
  assets:
    - assets/images/LogoUp.png
    - assets/images/QR.png
  uses-material-design: true
